apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2019-11-06T04:30:56Z'
  generation: 2
  labels:
    app: registros-2.0
  name: registros-2.0-v20.0.1
  namespace: default
  resourceVersion: '2973'
  selfLink: /apis/apps/v1/namespaces/default/deployments/registros-2.0
  uid: 39f9fed8-004e-11ea-9a8c-42010a800038
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: registros-2.0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: registros-2.0
    spec:
      containers:
        - image: nginx:latest
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-11-06T04:31:06Z'
      lastUpdateTime: '2019-11-06T04:31:06Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2019-11-06T04:30:56Z'
      lastUpdateTime: '2019-11-06T04:31:06Z'
      message: ReplicaSet "registros-2.0-7f458dc77c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
